# Generated by Django 3.1.7 on 2021-04-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tarea',
            new_name='tar',
        ),
    ]
