# Generated by Django 3.1.7 on 2021-04-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cout', '0002_auto_20210422_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tar',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='name',
        ),
    ]
